siteUid: null
sortOrder: 3
template: /freeform/bootstrap/edit_submission
uriParts:
  - freeform/bootstrap/
  -
    - slug
    - '[^\/]+'
  - /submissions/edit/
  -
    - token
    - \w+
uriPattern: 'freeform/bootstrap/<slug:[^\/]+>/submissions/edit/<token:\w+>'
