field: b02731a5-4105-4dbf-b19f-26510c3a0080
fieldLayouts:
  1659a484-2de9-41b4-8f53-5d86a5678ca6:
    tabs:
      -
        elements:
          -
            fieldUid: 16d50483-1909-462c-926f-6d03d5efee80
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  16d50483-1909-462c-926f-6d03d5efee80:
    contentColumnType: string
    fieldGroup: null
    handle: tab
    instructions: 'Carousel can have multiple tabs. You have to define the entries source for each tab'
    name: Tab
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 43a5129a-290b-49c4-a6f1-84ec574575a7
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_25_tab}}'
      fieldLayout: row
      maxRows: '4'
      minRows: '1'
      placeholderKey: null
      propagationMethod: all
      selectionLabel: Tab
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: carousel
name: Carousel
sortOrder: 2
