field: 11b198e7-27cf-4390-a11f-a7ff2f7f7bab
fieldLayouts:
  5cd02f93-dfbe-4e92-afbd-5df3a29c61ac:
    tabs:
      -
        elements:
          -
            fieldUid: 64e1ca10-f4ef-4d76-9dcd-69dfc405aeea
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 71a3106b-b9d3-4f02-bc4e-dbae1a384f29
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 615751a5-56bf-4aea-ab25-bfa3663e0d3b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b6b7131b-832f-415d-8e53-cf53c372e1c1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: af319a9b-9a99-482e-b838-b6ab6f1192d3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: a99ab3d7-09fd-42f2-a0d0-b2c0a6bd849b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  615751a5-56bf-4aea-ab25-bfa3663e0d3b:
    contentColumnType: text
    fieldGroup: null
    handle: criteria
    instructions: ''
    name: Criteria
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  64e1ca10-f4ef-4d76-9dcd-69dfc405aeea:
    contentColumnType: text
    fieldGroup: null
    handle: categoryName
    instructions: ''
    name: 'Category Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  71a3106b-b9d3-4f02-bc4e-dbae1a384f29:
    contentColumnType: string
    fieldGroup: null
    handle: categoryGroup
    instructions: ''
    name: 'Category Group'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Spas & Treatments'
            -
              - value
              - spasTreatments
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Wellness Travel'
            -
              - value
              - wellnessTravel
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Skincare & Style'
            -
              - value
              - skincareStyle
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Fitness & Well-Being'
            -
              - value
              - fitnessWellBeing
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'People & Community'
            -
              - value
              - peopleCommunity
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  a99ab3d7-09fd-42f2-a0d0-b2c0a6bd849b:
    contentColumnType: string
    fieldGroup: null
    handle: winnerPhoto
    instructions: ''
    name: 'Winner Photo'
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:194b5683-b6c3-4ff1-a61f-842f605a95a6'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  af319a9b-9a99-482e-b838-b6ab6f1192d3:
    contentColumnType: text
    fieldGroup: null
    handle: winners
    instructions: ''
    name: Winners
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b6b7131b-832f-415d-8e53-cf53c372e1c1:
    contentColumnType: text
    fieldGroup: null
    handle: nominations
    instructions: ''
    name: Nominations
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: cateogry
name: Category
sortOrder: 1
