field: 49c5d010-deb6-4e8a-baa7-ad2d87b82917
fieldLayouts:
  66f90342-7189-4eae-8b50-9f913762091b:
    tabs:
      -
        elements:
          -
            fieldUid: db5dc28b-21d2-4b09-8ff2-a8a846b0c884
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 10ad73b7-4db2-4650-8f67-d941394a16ef
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  10ad73b7-4db2-4650-8f67-d941394a16ef:
    contentColumnType: boolean
    fieldGroup: null
    handle: showLink
    instructions: ''
    name: 'Show Link?'
    searchable: false
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  db5dc28b-21d2-4b09-8ff2-a8a846b0c884:
    contentColumnType: string
    fieldGroup: null
    handle: category
    instructions: ''
    name: Category
    searchable: false
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      branchLimit: '1'
      limit: null
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: 'group:b85be20d-3d22-431f-a700-c2d63cf40881'
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
handle: category
name: Category
sortOrder: 2
