field: 43a5129a-290b-49c4-a6f1-84ec574575a7
fieldLayouts:
  8a2687d6-513c-46fe-a176-30ec36fd3f12:
    tabs:
      -
        elements:
          -
            fieldUid: fddf411a-b093-4462-b944-517df7919682
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  fddf411a-b093-4462-b944-517df7919682:
    contentColumnType: string
    fieldGroup: null
    handle: entry
    instructions: ''
    name: Entry
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '12'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources:
        - 'section:c2929640-5995-4a0b-b490-deb3c54ab6d4'
        - 'section:5e15a326-1e20-4d38-86df-6f2bc3183b14'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: custom
name: Custom
sortOrder: 5
