field: 1e9a7d45-d736-498b-a1ac-5f9e110553c9
fieldLayouts:
  5a4987d2-1544-449a-9c9d-862cf161b585:
    tabs:
      -
        elements:
          -
            fieldUid: e124bf60-25f6-48bd-a1d6-61d11c7c71f6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  e124bf60-25f6-48bd-a1d6-61d11c7c71f6:
    contentColumnType: text
    fieldGroup: null
    handle: adgroup
    instructions: ''
    name: Adgroup
    searchable: false
    translationKeyFormat: null
    translationMethod: none
    type: doublesecretagency\adwizard\fields\AdGroups
handle: desktopAdgroup
name: 'Desktop Adgroup'
sortOrder: 1
