field: 87027a3c-765e-4329-90d4-193dc2188fed
fieldLayouts:
  38a8faf4-cb74-4da6-89cb-41da45835464:
    tabs:
      -
        elements:
          -
            fieldUid: 511f3915-ffce-4bcc-8ec7-d561bf9746af
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  511f3915-ffce-4bcc-8ec7-d561bf9746af:
    contentColumnType: text
    fieldGroup: null
    handle: adgroup
    instructions: ''
    name: Adgroup
    searchable: false
    translationKeyFormat: null
    translationMethod: none
    type: doublesecretagency\adwizard\fields\AdGroups
handle: desktopAdgroup
name: 'Desktop Adgroup'
sortOrder: 1
