field: a9f00eab-73ff-4659-9b15-ee56aa8c8531
fieldLayouts:
  6eb80157-a127-4912-8d1a-f5aaf46406aa:
    tabs:
      -
        elements:
          -
            fieldUid: d340c22e-dda8-405e-af37-9afbf1634e44
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b24aec88-d28a-42d9-9eea-87887195be9f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a7e7adde-f2bd-4f58-bac0-14f5b6c2a643
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8b5a104d-c67c-4030-9843-11ad9a3a1012
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8b5a104d-c67c-4030-9843-11ad9a3a1012:
    contentColumnType: string
    fieldGroup: null
    handle: calendar
    instructions: ''
    name: Calendar
    searchable: false
    settings:
      allDay: false
      endDate: null
      endRepeat: null
      endRepeatDate: null
      months: null
      repeatType: null
      repeats: false
      startDate: null
    translationKeyFormat: null
    translationMethod: none
    type: unionco\calendarize\fields\CalendarizeField
  a7e7adde-f2bd-4f58-bac0-14f5b6c2a643:
    contentColumnType: text
    fieldGroup: null
    handle: location
    instructions: ''
    name: Location
    searchable: false
    settings:
      boundary: '""'
      boundaryRestrictionNELat: null
      boundaryRestrictionNELng: null
      boundaryRestrictionSWLat: null
      boundaryRestrictionSWLng: null
      country: null
      countryRestriction: null
      height: null
      hideAddress: ''
      hideLatLng: null
      hideMap: ''
      hideSearch: ''
      lat: 51.272154
      lng: 0.514951
      maxZoom: '18'
      minZoom: '3'
      showCurrentLocation: ''
      showLatLng: ''
      showW3WField: false
      showW3WGrid: false
      size: normal
      typeRestriction: null
      zoom: 15
    translationKeyFormat: null
    translationMethod: none
    type: ether\simplemap\fields\MapField
  b24aec88-d28a-42d9-9eea-87887195be9f:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d340c22e-dda8-405e-af37-9afbf1634e44:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: event
name: Event
sortOrder: 9
