field: a9f00eab-73ff-4659-9b15-ee56aa8c8531
fieldLayouts:
  e5b54909-cc62-4c99-80c1-6f0746748fb2:
    tabs:
      -
        elements:
          -
            fieldUid: a3d41890-6851-45de-8d47-b1e6a809da40
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b955502d-2b5f-48fa-b90f-5cc740cb4fd5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4a336fb2-d2ca-4881-9be7-c91acb061b37
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4a336fb2-d2ca-4881-9be7-c91acb061b37:
    contentColumnType: string
    fieldGroup: null
    handle: form
    instructions: ''
    name: Form
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: barrelstrength\sproutforms\fields\Forms
  a3d41890-6851-45de-8d47-b1e6a809da40:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b955502d-2b5f-48fa-b90f-5cc740cb4fd5:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: form
name: Form
sortOrder: 9
