field: a9f00eab-73ff-4659-9b15-ee56aa8c8531
fieldLayouts:
  e5b54909-cc62-4c99-80c1-6f0746748fb2:
    tabs:
      -
        elements:
          -
            fieldUid: 4a336fb2-d2ca-4881-9be7-c91acb061b37
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4a336fb2-d2ca-4881-9be7-c91acb061b37:
    contentColumnType: string
    fieldGroup: null
    handle: form
    instructions: ''
    name: Form
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\formie\fields\Forms
handle: form
name: Form
sortOrder: 10
