field: 13772a04-9e7b-48fd-bfea-292b51023c16
fieldLayouts:
  9c4cf2cc-9854-4eb3-8764-fecbde0830cd:
    tabs:
      -
        elements:
          -
            fieldUid: e7981f83-9359-45ef-bd25-e22195997031
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  e7981f83-9359-45ef-bd25-e22195997031:
    contentColumnType: string
    fieldGroup: null
    handle: form
    instructions: ''
    name: Form
    searchable: false
    settings:
      errorMessage: 'Component class ''Solspace\Freeform\FieldTypes\FormFieldType'' belongs to a disabled plugin (Freeform).'
      expectedType: Solspace\Freeform\FieldTypes\FormFieldType
      settings: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MissingField
handle: form
name: Form
sortOrder: 3
