field: a9f00eab-73ff-4659-9b15-ee56aa8c8531
fieldLayouts:
  a3fd56ae-c637-4a7f-883e-4651909071a6:
    tabs:
      -
        elements:
          -
            fieldUid: b4d06e18-4a8c-4d72-8e3c-61038bd38b68
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b4d06e18-4a8c-4d72-8e3c-61038bd38b68:
    contentColumnType: string
    fieldGroup: null
    handle: gallery
    instructions: ''
    name: Gallery
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - c7853873-dc07-4748-90ff-6bb32d1b269d
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 475ee74b-a539-4e6e-8e80-d4d24a18df18
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_4_gallery}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: gallery
name: Gallery
sortOrder: 2
