field: a9f00eab-73ff-4659-9b15-ee56aa8c8531
fieldLayouts:
  b1fff65a-9a5c-4677-a4d6-d7bf7885ad75:
    tabs:
      -
        elements:
          -
            fieldUid: 14f00e2f-aa39-4c46-a291-51bfe9523172
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4be7265a-1f2f-4bbe-a6e2-10d0cfccb205
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  14f00e2f-aa39-4c46-a291-51bfe9523172:
    contentColumnType: boolean
    fieldGroup: null
    handle: showNumber
    instructions: ''
    name: 'Show Number'
    searchable: false
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  4be7265a-1f2f-4bbe-a6e2-10d0cfccb205:
    contentColumnType: string
    fieldGroup: null
    handle: listicle
    instructions: ''
    name: Listicle
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - bf8d9686-a59f-47ab-88e7-f52608216e2b
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 17b940bb-1abe-4368-9ccd-ba94b9d5257a
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 4e7f0a84-494e-4c94-836a-1fc0a77db557
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 81ffaa57-a57c-43a1-abfc-c810f668fcd2
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_10_listicle}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: listicle
name: Listicle
sortOrder: 11
