field: a9f00eab-73ff-4659-9b15-ee56aa8c8531
fieldLayouts:
  a0ad353e-2231-46ab-a9e1-a365b29ac9c9:
    tabs:
      -
        elements:
          -
            fieldUid: 3adbe5ba-01d1-429b-b122-fe8136ed8f83
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c655c1d8-77b4-4a22-b313-cb4a31a2e90a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3718429c-9ead-4040-9d70-a038b65c66ff
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3718429c-9ead-4040-9d70-a038b65c66ff:
    contentColumnType: text
    fieldGroup: null
    handle: richTextEditor
    instructions: ''
    name: 'Rich Text Editor'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes:
        - 883ab42c-10f1-4e32-a559-61f23e4e3775
        - 9f801622-9f26-40c9-9126-ac4041a76554
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  3adbe5ba-01d1-429b-b122-fe8136ed8f83:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c655c1d8-77b4-4a22-b313-cb4a31a2e90a:
    contentColumnType: string
    fieldGroup: null
    handle: slides
    instructions: ''
    name: Slides
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
        - 'volume:9f801622-9f26-40c9-9126-ac4041a76554'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: listicleImageSlider
name: 'Listicle / Image Slider'
sortOrder: 15
