field: a9f00eab-73ff-4659-9b15-ee56aa8c8531
fieldLayouts:
  f66b3a6c-d472-4ce4-8e1d-691dc27168ab:
    tabs:
      -
        elements:
          -
            fieldUid: d71ed07a-ebb1-4333-8762-cc04eefb94ac
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c41ab32e-3d88-4cbe-8a59-461931cb1c3f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9e5c7af3-6ae1-4a54-a032-7148d75d2fcd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9e8cd4da-1366-4314-9dec-5b536472010b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a5651584-369d-4b97-9b6b-1cd16d4e35b4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9e5c7af3-6ae1-4a54-a032-7148d75d2fcd:
    contentColumnType: text
    fieldGroup: null
    handle: itemName
    instructions: ''
    name: 'Item Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9e8cd4da-1366-4314-9dec-5b536472010b:
    contentColumnType: string(255)
    fieldGroup: null
    handle: hyperlink
    instructions: ''
    name: Hyperlink
    searchable: false
    settings:
      maxLength: '255'
      placeholder: 'https://www.google.com'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  a5651584-369d-4b97-9b6b-1cd16d4e35b4:
    contentColumnType: text
    fieldGroup: null
    handle: richTextEditor
    instructions: ''
    name: 'Rich Text Editor'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c41ab32e-3d88-4cbe-8a59-461931cb1c3f:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'White / Transparent Background Only.'
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
        - 'volume:9f801622-9f26-40c9-9126-ac4041a76554'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d71ed07a-ebb1-4333-8762-cc04eefb94ac:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: listicleSingleProduct
name: 'Listicle / Single Product'
sortOrder: 17
