field: a9f00eab-73ff-4659-9b15-ee56aa8c8531
fieldLayouts:
  95113fe0-7997-4f99-8b88-d19f9196d992:
    tabs:
      -
        elements:
          -
            fieldUid: 61c5a781-1a79-45ec-ae7b-615ff7152533
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 66ca315e-534a-4a16-b934-0419a88cd7a1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7afc02fc-2288-4e0f-a4b6-180a4023a071
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  61c5a781-1a79-45ec-ae7b-615ff7152533:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  66ca315e-534a-4a16-b934-0419a88cd7a1:
    contentColumnType: text
    fieldGroup: null
    handle: embed
    instructions: ''
    name: Embed
    searchable: false
    settings:
      url: ''
    translationKeyFormat: null
    translationMethod: none
    type: wrav\oembed\fields\OembedField
  7afc02fc-2288-4e0f-a4b6-180a4023a071:
    contentColumnType: text
    fieldGroup: null
    handle: richTextEditor
    instructions: ''
    name: 'Rich Text Editor'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes:
        - 883ab42c-10f1-4e32-a559-61f23e4e3775
        - 9f801622-9f26-40c9-9126-ac4041a76554
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: listicleEmbed
name: 'Listicle / Embed'
sortOrder: 15
