field: 1e9a7d45-d736-498b-a1ac-5f9e110553c9
fieldLayouts:
  92c88798-c305-4ed4-acfa-01c24ae4c3f1:
    tabs:
      -
        elements:
          -
            fieldUid: 2868f2c1-69cd-4de0-b013-1a55d8f4940e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2868f2c1-69cd-4de0-b013-1a55d8f4940e:
    contentColumnType: text
    fieldGroup: null
    handle: adgroup
    instructions: ''
    name: Adgroup
    searchable: false
    translationKeyFormat: null
    translationMethod: none
    type: doublesecretagency\adwizard\fields\AdGroups
handle: mobileAdgroup
name: 'Mobile Adgroup'
sortOrder: 2
