field: cdfac713-f7e7-4e44-9e62-d218d76ab674
fieldLayouts:
  d5be3664-5a38-4136-8446-f3c5b743f11f:
    tabs:
      -
        elements:
          -
            fieldUid: 11728799-c286-4a93-bb92-03552f7d8eb9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  11728799-c286-4a93-bb92-03552f7d8eb9:
    contentColumnType: text
    fieldGroup: null
    handle: adgroup
    instructions: ''
    name: Adgroup
    searchable: false
    translationKeyFormat: null
    translationMethod: none
    type: doublesecretagency\adwizard\fields\AdGroups
handle: mobileAdgroup
name: 'Mobile Adgroup'
sortOrder: 2
