field: 51f3339a-5e27-4c65-95cf-82085401023d
fieldLayouts:
  31c26b24-b929-4087-81c7-a0b5526273d2:
    tabs:
      -
        elements:
          -
            fieldUid: 717c9e87-1ead-48d2-a195-264717a2edcd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 039d64d6-bca3-4c7e-89a0-532b5cf728e3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  039d64d6-bca3-4c7e-89a0-532b5cf728e3:
    contentColumnType: string
    fieldGroup: null
    handle: heroImage
    instructions: ''
    name: 'Hero Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
        - 'volume:9f801622-9f26-40c9-9126-ac4041a76554'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  717c9e87-1ead-48d2-a195-264717a2edcd:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: newsletterSubscription
name: 'Newsletter Subscription'
sortOrder: 5
