field: a9f00eab-73ff-4659-9b15-ee56aa8c8531
fieldLayouts:
  2d9f1335-eeae-484f-a6ea-9d5fad23adab:
    tabs:
      -
        elements:
          -
            fieldUid: b7bf6b01-6b0b-4d48-9c31-63404b36a897
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b7bf6b01-6b0b-4d48-9c31-63404b36a897:
    contentColumnType: string
    fieldGroup: null
    handle: qA
    instructions: ''
    name: 'Q&A'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - eadd3e1f-b95d-41b6-b97f-a1c004bea539
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 959a1ff6-acd6-4f01-912a-902eee53050a
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_11_qa}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: qA
name: 'Q&A'
sortOrder: 10
