field: 51f3339a-5e27-4c65-95cf-82085401023d
fieldLayouts:
  530dce51-eb38-4f14-887a-7cedd19c4e48:
    tabs:
      -
        elements:
          -
            fieldUid: 1a3a3163-37ed-4004-aece-697b593dd10f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3785f85a-d93b-47a3-aa02-003f4edef64f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  1a3a3163-37ed-4004-aece-697b593dd10f:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Only the first source will be used'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3785f85a-d93b-47a3-aa02-003f4edef64f:
    contentColumnType: string
    fieldGroup: null
    handle: stories
    instructions: 'Max 12 Entries'
    name: Stories
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '12'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources:
        - 'section:5e15a326-1e20-4d38-86df-6f2bc3183b14'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: storyCarousel
name: 'Story Carousel'
sortOrder: 2
