field: 51f3339a-5e27-4c65-95cf-82085401023d
fieldLayouts:
  c4e54f58-58c9-410c-aa24-7cbd179b43ee:
    tabs:
      -
        elements:
          -
            fieldUid: f42799bb-710a-462a-9c2c-bef4a6b92c26
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0f76637a-5172-4397-aa8c-2cfbc9f7ebcd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 4ea4fb28-13d9-4c5c-b2f9-fece1ed0e9cf
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0f76637a-5172-4397-aa8c-2cfbc9f7ebcd:
    contentColumnType: string
    fieldGroup: null
    handle: sourceStories
    instructions: 'Max 4 stories'
    name: 'Source - Stories'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '4'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources:
        - 'section:5e15a326-1e20-4d38-86df-6f2bc3183b14'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  4ea4fb28-13d9-4c5c-b2f9-fece1ed0e9cf:
    contentColumnType: boolean
    fieldGroup: null
    handle: rtl
    instructions: ''
    name: 'From Right to Left'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  f42799bb-710a-462a-9c2c-bef4a6b92c26:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Only the first source will be used'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: storyGallery
name: 'Story Gallery'
sortOrder: 3
