field: 51f3339a-5e27-4c65-95cf-82085401023d
fieldLayouts:
  c4e54f58-58c9-410c-aa24-7cbd179b43ee:
    tabs:
      -
        elements:
          -
            fieldUid: f42799bb-710a-462a-9c2c-bef4a6b92c26
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 0f76637a-5172-4397-aa8c-2cfbc9f7ebcd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bc3fd734-3f25-4e27-976f-90b86e217f78
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0f76637a-5172-4397-aa8c-2cfbc9f7ebcd:
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: 'Max 4 Entries'
    name: Entries
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 966c12fd-d63c-47b6-a024-8bea37fb7a21
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_24_entries}}'
      fieldLayout: table
      maxRows: '1'
      minRows: '1'
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: '1'
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  bc3fd734-3f25-4e27-976f-90b86e217f78:
    contentColumnType: boolean
    fieldGroup: null
    handle: rtl
    instructions: 'Layout directing change.'
    name: 'From Right to Left'
    searchable: false
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  f42799bb-710a-462a-9c2c-bef4a6b92c26:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: storyGallery
name: 'Story Gallery'
sortOrder: 3
