field: 51f3339a-5e27-4c65-95cf-82085401023d
fieldLayouts:
  530dce51-eb38-4f14-887a-7cedd19c4e48:
    tabs:
      -
        elements:
          -
            fieldUid: 1a3a3163-37ed-4004-aece-697b593dd10f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: dcf1654e-9b1b-4f81-a2ae-5d31c5750d25
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1a3a3163-37ed-4004-aece-697b593dd10f:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dcf1654e-9b1b-4f81-a2ae-5d31c5750d25:
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: 'Max 12 Entries'
    name: Entries
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 49c5d010-deb6-4e8a-baa7-ad2d87b82917
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_16_entries}}'
      fieldLayout: table
      maxRows: '1'
      minRows: '1'
      placeholderKey: null
      propagationMethod: all
      selectionLabel: Source
      staticField: '1'
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: storyCarousel
name: 'Story Carousel'
sortOrder: 2
