field: 25ae8551-db14-40c5-9631-e1352ff4b706
fieldLayouts:
  01d15c76-08f7-4225-8da1-5648e1571c7e:
    tabs:
      -
        elements:
          -
            fieldUid: 8ddcc4b4-4584-4798-8624-b30e0f70754f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bcbdc31e-52e0-4ce6-9bc8-ff7f558ead0f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8ddcc4b4-4584-4798-8624-b30e0f70754f:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  bcbdc31e-52e0-4ce6-9bc8-ff7f558ead0f:
    contentColumnType: text
    fieldGroup: null
    handle: richTextEditor
    instructions: ''
    name: 'Rich Text Editor'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes:
        - 883ab42c-10f1-4e32-a559-61f23e4e3775
        - 9f801622-9f26-40c9-9126-ac4041a76554
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: tab
name: Tab
sortOrder: 1
