field: 966c12fd-d63c-47b6-a024-8bea37fb7a21
fieldLayouts:
  f80bc675-cc2c-4f75-8951-a5b184c7db17:
    tabs:
      -
        elements:
          -
            fieldUid: 9208956d-3bc8-4e8d-aea1-f823e3d29d80
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 010f32ee-ce9d-4125-9d5f-c156e538b0a2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  010f32ee-ce9d-4125-9d5f-c156e538b0a2:
    contentColumnType: boolean
    fieldGroup: null
    handle: showLink
    instructions: ''
    name: 'Show Link?'
    searchable: false
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  9208956d-3bc8-4e8d-aea1-f823e3d29d80:
    contentColumnType: string
    fieldGroup: null
    handle: tag
    instructions: ''
    name: Tag
    searchable: false
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      branchLimit: '1'
      limit: null
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: 'group:dc068a49-9607-4bc7-9bd1-069f279dbf76'
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
handle: tag
name: Tag
sortOrder: 4
