field: 49c5d010-deb6-4e8a-baa7-ad2d87b82917
fieldLayouts:
  817fae0f-663b-4181-9f46-287f2e895ca6:
    tabs:
      -
        elements:
          -
            fieldUid: 578288e2-3161-4d9c-b149-187d465c74e4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: bb636d0c-40b7-45b0-b554-130b216730c4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  578288e2-3161-4d9c-b149-187d465c74e4:
    contentColumnType: string
    fieldGroup: null
    handle: tag
    instructions: ''
    name: Tag
    searchable: false
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      branchLimit: ''
      limit: null
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: 'group:dc068a49-9607-4bc7-9bd1-069f279dbf76'
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  bb636d0c-40b7-45b0-b554-130b216730c4:
    contentColumnType: boolean
    fieldGroup: null
    handle: showLink
    instructions: ''
    name: 'Show Link?'
    searchable: false
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: tag
name: Tag
sortOrder: 4
