fieldLayouts:
  c017554b-8099-4511-98a6-44692aa06169:
    tabs:
      -
        elements:
          -
            fieldUid: 99e91804-a574-459e-bda8-3a6db0268750
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 72162939-52e4-47fb-b997-6a6d8947ca17
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: user
name: User
