fieldLayouts:
  946c8901-a593-48c5-9e33-438afcca6841:
    tabs:
      -
        elements:
          -
            heading: null
            type: craft\fieldlayoutelements\Heading
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: b357d9dd-f6da-4d5f-b00f-8769518e1b39
            instructions: ''
            label: Standfirst
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3f41492f-97e1-4608-8456-655f094e4284
            instructions: ''
            label: 'Sponsor Note'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 65bad440-2ce9-4205-93f3-4f17fc67fa67
            instructions: 'Double Click to edit Bio & upload profile pic.'
            label: Byline
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: 'Hero Image'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 02d38f73-db56-4fab-a533-0dc7400f81fe
            instructions: ''
            label: 'Hero Image'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: c704e0b8-fa98-4653-a2a2-ef9937e6764a
            instructions: ''
            label: 'Landscape Mode'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            heading: Content
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 3c6974ea-4e49-4ab8-a603-0751e5cfd4bf
            instructions: ''
            label: 'Set Number for Listicles'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a9f00eab-73ff-4659-9b15-ee56aa8c8531
            instructions: ''
            label: 'Story Content'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: aa058ac8-5cdd-4c29-8ea3-19f5c15ff138
            instructions: ''
            label: Credit
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Main Content'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: ddbc3373-03b2-4ff9-a616-05ad1683a032
            instructions: ''
            label: Category
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 10f6975d-b749-4638-ac0b-6bf072495899
            instructions: ''
            label: 'Print Issue'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 07b4d748-dabf-4fd7-9bc1-e3fd5015b52b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Relation
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 68752c4e-cc58-4744-a1c4-20778860741f
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 3
handle: generic
hasTitleField: true
name: Generic
section: 5e15a326-1e20-4d38-86df-6f2bc3183b14
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
