fieldLayouts:
  3e0f3127-6064-440e-a098-78b95b5a3b0d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 51f3339a-5e27-4c65-95cf-82085401023d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Builder'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 0d1b7668-3611-4ad7-b03c-50cdd6a731cc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b02731a5-4105-4dbf-b19f-26510c3a0080
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Builder Old'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 68752c4e-cc58-4744-a1c4-20778860741f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 3
handle: home
hasTitleField: true
name: Home
section: 73c18577-4ee7-4d1d-be3f-133db7de04c5
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
