fieldLayouts:
  3f05a583-410b-45e3-aef1-96109b4c2fd0:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: fd0ad5a0-16ef-4f56-bb49-4dade6d51464
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 12570f9f-d945-4b47-b469-2c11fb90b92a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: e4e2cbc9-862a-4e2a-b4fb-e39739cde12b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eaf56e37-6414-44dd-a6f3-0e50d529ba0b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 525b88d9-2a89-4888-b90c-2224c45fb39f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: asiaspaAwardsCategory
name: 'AsiaSpa Award Category'
siteSettings:
  5058e36f-39fa-4fe2-982d-2a6082be4a27:
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 2
  uid: f30b450e-76d4-4030-9926-ce8d2938946c
