fieldLayouts:
  3bed36fd-f338-46d6-8082-385190f1388a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 51f3339a-5e27-4c65-95cf-82085401023d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 68752c4e-cc58-4744-a1c4-20778860741f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 0d1b7668-3611-4ad7-b03c-50cdd6a731cc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 3'
        sortOrder: 3
handle: printIssue
name: 'Print Issue'
siteSettings:
  5058e36f-39fa-4fe2-982d-2a6082be4a27:
    hasUrls: true
    template: _categories/_category
    uriFormat: 'print-issue/{slug}'
structure:
  maxLevels: 1
  uid: d3a91e7b-dae5-4b4c-aa4b-54b1aeaee2f7
