tabs:
  -
    elements:
      -
        fieldUid: 72162939-52e4-47fb-b997-6a6d8947ca17
        instructions: 'User Bio will be shown when on /user/username pages.'
        label: 'User Bio'
        required: ''
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
    name: Profile
    sortOrder: 1
