tabs:
  -
    elements:
      -
        fieldUid: 2b2910be-51fe-4ca0-90cf-f38ca4db5c39
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
    name: Bio
    sortOrder: 1
