fieldLayouts:
  6e9132e6-5999-4842-9162-e98341c18d20:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: f406c8e9-d661-4a05-8ef1-5391cd2c6542
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 01689ff9-68b9-4f16-94b1-0e8fea805946
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 028882a5-b279-45fc-a193-a926b6e3c587
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 82762402-1c0c-4d11-84b8-036684f9ed74
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: googleCloudUnsplash
hasUrls: true
name: 'Google Cloud / Unsplash'
settings:
  bucket: asiaspa
  bucketSelectionMode: choose
  expires: ''
  keyFileContents: $GCS_KEY
  projectId: $GCS_PROJECT_ID
  subfolder: unsplash
sortOrder: 2
type: craft\googlecloud\Volume
url: $GCS_BASE_URL
