fieldLayouts:
  6e9132e6-5999-4842-9162-e98341c18d20:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: aa058ac8-5cdd-4c29-8ea3-19f5c15ff138
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: googleCloudUnsplash
hasUrls: true
name: 'Google Cloud / Unsplash'
settings:
  bucket: asiaspa
  bucketSelectionMode: choose
  expires: ''
  keyFileContents: $GCS_KEY
  projectId: $GCS_PROJECT_ID
  subfolder: unsplash
sortOrder: 2
type: craft\googlecloud\Volume
url: 'http://storage.googleapis.com/asiaspa/'
