fieldLayouts:
  15eda15a-60de-4828-ab0a-09024dde5786:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: f406c8e9-d661-4a05-8ef1-5391cd2c6542
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: googleCloudUpload
hasUrls: true
name: 'Google Cloud / Upload'
settings:
  bucket: asiaspa
  bucketSelectionMode: choose
  expires: ''
  keyFileContents: $GCS_KEY
  projectId: $GCS_PROJECT_ID
  subfolder: upload
sortOrder: 1
type: craft\googlecloud\Volume
url: $GCS_BASE_URL
