fieldLayouts:
  8508aaff-38d7-4693-b873-4ea707960a14:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: serverStorage
hasUrls: true
name: 'Server Storage'
settings:
  path: '@webroot/asset'
sortOrder: 9
type: craft\volumes\Local
url: '@web/asset'
