contentColumnType: string
fieldGroup: 3c7968d3-974b-4238-bfe2-0dfcefb8ce1e
handle: addressSmartMap
instructions: ''
name: 'address - smart map'
searchable: false
settings:
  dragPinDefault: ''
  dragPinLatitude: '0'
  dragPinLongitude: '0'
  dragPinZoom: '4'
  layout:
    __assoc__:
      -
        - street1
        -
          __assoc__:
            -
              - width
              - 100
            -
              - enable
              - 1
            -
              - position
              - 1
      -
        - street2
        -
          __assoc__:
            -
              - width
              - 100
            -
              - enable
              - 1
            -
              - position
              - 2
      -
        - city
        -
          __assoc__:
            -
              - width
              - 50
            -
              - enable
              - 1
            -
              - position
              - 3
      -
        - state
        -
          __assoc__:
            -
              - width
              - 15
            -
              - enable
              - 1
            -
              - position
              - 4
      -
        - zip
        -
          __assoc__:
            -
              - width
              - 35
            -
              - enable
              - 1
            -
              - position
              - 5
      -
        - country
        -
          __assoc__:
            -
              - width
              - 100
            -
              - enable
              - 1
            -
              - position
              - 6
      -
        - lat
        -
          __assoc__:
            -
              - width
              - 50
            -
              - enable
              - 1
            -
              - position
              - 7
      -
        - lng
        -
          __assoc__:
            -
              - width
              - 50
            -
              - enable
              - 1
            -
              - position
              - 8
translationKeyFormat: null
translationMethod: none
type: doublesecretagency\smartmap\fields\Address
