contentColumnType: text
fieldGroup: 6ebe0a75-3257-417d-8c9b-c712a8dbf9c9
handle: adgroupDesktop
instructions: ''
name: 'Adgroup - Desktop'
searchable: false
translationKeyFormat: null
translationMethod: none
type: doublesecretagency\adwizard\fields\AdGroups
