contentColumnType: text
fieldGroup: 0a3d02f5-f5e6-4b6e-85c4-e6f83226cf91
handle: adPremiumLeaderboard
instructions: 728x90
name: 'Ad Premium Leaderboard'
searchable: false
translationKeyFormat: null
translationMethod: none
type: doublesecretagency\adwizard\fields\AdGroups
