contentColumnType: text
fieldGroup: c988c230-88d1-42da-86a6-8a60a7a243f8
handle: asiaspaAwardsCategoryNominees
instructions: ''
name: 'AsiaSpa Awards - Category -  Nominees'
searchable: true
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Title
            -
              - handle
              - title
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
