contentColumnType: string
fieldGroup: c988c230-88d1-42da-86a6-8a60a7a243f8
handle: asiaspaAwardsEventGallery
instructions: ''
name: 'AsiaSpa Awards - Event Gallery'
searchable: false
settings:
  allowSelfRelations: false
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:194b5683-b6c3-4ff1-a61f-842f605a95a6'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:194b5683-b6c3-4ff1-a61f-842f605a95a6'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
