contentColumnType: string
fieldGroup: c988c230-88d1-42da-86a6-8a60a7a243f8
handle: asiaspaAwardsSponsorship
instructions: ''
name: 'AsiaSpa Awards - Sponsorship'
searchable: false
settings:
  contentTable: '{{%matrixcontent_asiaspaawardssponsorship}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
