contentColumnType: string
fieldGroup: c988c230-88d1-42da-86a6-8a60a7a243f8
handle: asiaspaAwardsAwardsCategories
instructions: ''
name: 'AsiaSpa Awards - Awards Categories'
searchable: true
settings:
  contentTable: '{{%matrixcontent_asiaspaawardsawardscategories}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
