contentColumnType: string
fieldGroup: c988c230-88d1-42da-86a6-8a60a7a243f8
handle: asiaspaAwardsOtherJudges
instructions: ''
name: 'AsiaSpa Awards - Other Judges'
searchable: false
settings:
  contentTable: '{{%stc_asiaspaawardsotherjudges}}'
  fieldLayout: row
  maxRows: ''
  minRows: ' 0'
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
