contentColumnType: integer
fieldGroup: c988c230-88d1-42da-86a6-8a60a7a243f8
handle: asiaspaAwardsEnterForm
instructions: ''
name: 'AsiaSpa Awards - Enter - Form'
searchable: false
translationKeyFormat: null
translationMethod: none
type: Solspace\Freeform\FieldTypes\FormFieldType
