contentColumnType: string
fieldGroup: c988c230-88d1-42da-86a6-8a60a7a243f8
handle: asiaspaAwardsAsiaspaJudges
instructions: ''
name: 'AsiaSpa Awards - AsiaSpa Judges'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: Judges
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Users
