contentColumnType: string
fieldGroup: 6ebe0a75-3257-417d-8c9b-c712a8dbf9c9
handle: assetUploadMultipleImages
instructions: ''
name: 'Asset - Upload - Multiple Images'
searchable: false
settings:
  allowSelfRelations: false
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
    - 'volume:9f801622-9f26-40c9-9126-ac4041a76554'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
