contentColumnType: string(7)
fieldGroup: b3d816bc-8f24-4620-9c29-3cabc185b44e
handle: assetUnsplashDominantColor
instructions: ''
name: 'Asset  - Unsplash - Dominant Color'
searchable: false
settings:
  defaultColor: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
