contentColumnType: string
fieldGroup: 6ebe0a75-3257-417d-8c9b-c712a8dbf9c9
handle: calendar
instructions: ''
name: Calendar
searchable: false
settings:
  allDay: false
  endDate: null
  endRepeat: null
  endRepeatDate: null
  months: null
  repeatType: null
  repeats: false
  startDate: null
translationKeyFormat: null
translationMethod: none
type: unionco\calendarize\fields\CalendarizeField
