contentColumnType: string(2000)
fieldGroup: 6ebe0a75-3257-417d-8c9b-c712a8dbf9c9
handle: contentDescription
instructions: ''
name: 'Content - Description'
searchable: true
settings:
  byteLimit: null
  charLimit: 500
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
