contentColumnType: text
fieldGroup: 6ebe0a75-3257-417d-8c9b-c712a8dbf9c9
handle: contentRichTextEditor
instructions: ''
name: 'Content - Rich Text Editor'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes:
    - 883ab42c-10f1-4e32-a559-61f23e4e3775
  cleanupHtml: true
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
