contentColumnType: string
fieldGroup: 6ebe0a75-3257-417d-8c9b-c712a8dbf9c9
handle: entrySource
instructions: ''
name: 'Entry - Source'
searchable: false
settings:
  contentTable: '{{%matrixcontent_entrysource}}'
  maxBlocks: '1'
  minBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
