contentColumnType: string
fieldGroup: 6ebe0a75-3257-417d-8c9b-c712a8dbf9c9
handle: homeHeroStory
instructions: ''
name: 'Home - Hero Story'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources:
    - 'section:5e15a326-1e20-4d38-86df-6f2bc3183b14'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
