contentColumnType: string(255)
fieldGroup: 6ebe0a75-3257-417d-8c9b-c712a8dbf9c9
handle: hyperlink
instructions: ''
name: Hyperlink
searchable: true
settings:
  maxLength: '255'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
