contentColumnType: string
fieldGroup: 3c7968d3-974b-4238-bfe2-0dfcefb8ce1e
handle: layoutBuilder
instructions: ''
name: 'Layout Builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_layoutbuilder}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
