contentColumnType: boolean
fieldGroup: 6ebe0a75-3257-417d-8c9b-c712a8dbf9c9
handle: lightswitch
instructions: ''
name: Lightswitch
searchable: false
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
