contentColumnType: string
fieldGroup: f6ccb015-3533-491f-8f9c-775d16605b99
handle: newsletterForm
instructions: ''
name: 'Newsletter - Form'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: verbb\formie\fields\Forms
