contentColumnType: text
fieldGroup: b3d816bc-8f24-4620-9c29-3cabc185b44e
handle: newsletterStandfirst
instructions: ''
name: 'Newsletter Standfirst'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
