contentColumnType: string
fieldGroup: 6ebe0a75-3257-417d-8c9b-c712a8dbf9c9
handle: pageBuilderOld
instructions: ''
name: 'Page Builder Old'
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagebuilderold}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
