contentColumnType: text
fieldGroup: 6ebe0a75-3257-417d-8c9b-c712a8dbf9c9
handle: pagesRichTextEditor
instructions: ''
name: 'Pages - Rich Text Editor'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes:
    - 883ab42c-10f1-4e32-a559-61f23e4e3775
    - 9f801622-9f26-40c9-9126-ac4041a76554
  cleanupHtml: true
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Standard.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
