contentColumnType: string(1000)
fieldGroup: 8cfd7cec-992b-4043-bab5-b9f4ac3bc2f9
handle: printIssueDigitalSubscriptionLink
instructions: ''
name: 'Print Issue - Digital Subscription Link'
searchable: false
settings:
  maxLength: '1000'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
