contentColumnType: integer
fieldGroup: a7b23ced-f8be-4c09-bba7-84b5e4552f75
handle: spaAsiaspaPerksForm
instructions: ''
name: 'Spa - AsiaSpa Perks - Form'
searchable: false
translationKeyFormat: null
translationMethod: none
type: Solspace\Freeform\FieldTypes\FormFieldType
