contentColumnType: text
fieldGroup: 3c7968d3-974b-4238-bfe2-0dfcefb8ce1e
handle: spaBuilder
instructions: ''
name: 'Spa Builder'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
