contentColumnType: string
fieldGroup: a7b23ced-f8be-4c09-bba7-84b5e4552f75
handle: spaLogo
instructions: 'White background only.'
name: 'Spa - Logo'
searchable: false
settings:
  allowSelfRelations: false
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Select the Hero Image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:571cb7c1-00fa-4aef-9106-c5f0d93ffd03'
  singleUploadLocationSubpath: '{slug}'
  source: null
  sources:
    - 'volume:571cb7c1-00fa-4aef-9106-c5f0d93ffd03'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
