contentColumnType: datetime
fieldGroup: a7b23ced-f8be-4c09-bba7-84b5e4552f75
handle: spaPromotionEndDate
instructions: ''
name: 'Spa - Promotion - End Date'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: true
  showTime: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
