contentColumnType: text
fieldGroup: a7b23ced-f8be-4c09-bba7-84b5e4552f75
handle: spaRichTextEditor
instructions: ''
name: 'Spa - Rich Text Editor'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes:
    - 571cb7c1-00fa-4aef-9106-c5f0d93ffd03
  cleanupHtml: true
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: standard.json
  purifyHtml: '1'
  redactorConfig: Standard.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
