contentColumnType: string
fieldGroup: a7b23ced-f8be-4c09-bba7-84b5e4552f75
handle: spaService
instructions: ''
name: 'Spa - Service'
searchable: false
settings:
  contentTable: '{{%matrixcontent_spaservice}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
