contentColumnType: string
fieldGroup: a7b23ced-f8be-4c09-bba7-84b5e4552f75
handle: spaTestimonal
instructions: ''
name: 'Spa - Testimonal '
searchable: false
settings:
  contentTable: '{{%matrixcontent_spatestimonal}}'
  maxBlocks: '1'
  minBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
