contentColumnType: boolean
fieldGroup: 847d91f3-2f4a-4f56-9f9d-40c20e080811
handle: storyListicleNumbering
instructions: ''
name: 'Story - Listicle Numbering'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
