contentColumnType: boolean
fieldGroup: 847d91f3-2f4a-4f56-9f9d-40c20e080811
handle: storyLandscape
instructions: "\r\n"
name: 'Story - Landscape'
searchable: false
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
