contentColumnType: text
fieldGroup: 847d91f3-2f4a-4f56-9f9d-40c20e080811
handle: storyByline
instructions: ''
name: 'Story - Byline'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
