contentColumnType: boolean
fieldGroup: 847d91f3-2f4a-4f56-9f9d-40c20e080811
handle: storyHeroImageOrientation
instructions: 'Switch to Landscape style (larger image)'
name: 'Story - Hero Image Orientation'
searchable: false
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
