contentColumnType: string
fieldGroup: 847d91f3-2f4a-4f56-9f9d-40c20e080811
handle: storyBuilder
instructions: ''
name: 'Story - Builder'
searchable: true
settings:
  contentTable: '{{%matrixcontent_storybuilder_1}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
