contentColumnType: string
fieldGroup: 847d91f3-2f4a-4f56-9f9d-40c20e080811
handle: storyHeroImageOrientation
instructions: ''
name: 'Story - Hero Image Orientation'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Portrait
        -
          - value
          - portrait
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Landscape
        -
          - value
          - landscape
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
