contentColumnType: string
fieldGroup: 847d91f3-2f4a-4f56-9f9d-40c20e080811
handle: storyHeroImage
instructions: ''
name: 'Story - Hero Image'
searchable: false
settings:
  allowSelfRelations: false
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Select the Hero Image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:4a49b85a-e6f1-4ee3-8085-cbfb50f5ce42'
  singleUploadLocationSubpath: 'story/{slug}'
  source: null
  sources:
    - 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
    - 'volume:9f801622-9f26-40c9-9126-ac4041a76554'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
