contentColumnType: string(200)
fieldGroup: e90928b8-0894-4ab9-ab3f-9ca369f52f3e
handle: userTitle
instructions: 'Job title / Post title ..etc'
name: 'User - Title'
searchable: false
settings:
  byteLimit: null
  charLimit: 50
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
