contentColumnType: string(7)
fieldGroup: f6ccb015-3533-491f-8f9c-775d16605b99
handle: websiteColorPrimary100
instructions: ''
name: 'Website - Color - Primary 100'
searchable: false
settings:
  defaultColor: '#f7f5f3'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
