contentColumnType: string(7)
fieldGroup: f6ccb015-3533-491f-8f9c-775d16605b99
handle: websiteColorPrimary900
instructions: ''
name: 'Website - Color - Primary 900'
searchable: false
settings:
  defaultColor: '#2d2218'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
