contentColumnType: string(7)
fieldGroup: f6ccb015-3533-491f-8f9c-775d16605b99
handle: websiteColorSecondary500
instructions: ''
name: 'Website - Color - Secondary 500'
searchable: false
settings:
  defaultColor: '#dfac76'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
