contentColumnType: text
fieldGroup: f6ccb015-3533-491f-8f9c-775d16605b99
handle: websiteSansSerifFontFontName
instructions: ''
name: 'Website - Sans Serif Font - Font Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
