contentColumnType: string
fieldGroup: f6ccb015-3533-491f-8f9c-775d16605b99
handle: websiteSansSerifFontBoldFontWeight
instructions: ''
name: 'Website - Sans Serif Font - Bold Font Weight'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - '100'
        -
          - value
          - '100'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '200'
        -
          - value
          - '200'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '300'
        -
          - value
          - '300'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '400'
        -
          - value
          - '400'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '500'
        -
          - value
          - '500'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '600'
        -
          - value
          - '600'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '700'
        -
          - value
          - '700'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '800'
        -
          - value
          - '800'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '900'
        -
          - value
          - '900'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
