contentColumnType: string(7)
fieldGroup: f6ccb015-3533-491f-8f9c-775d16605b99
handle: websiteColorPrimary300
instructions: ''
name: 'Website - Color - Primary 300'
searchable: false
settings:
  defaultColor: '#eed4b8'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
