contentColumnType: string(7)
fieldGroup: f6ccb015-3533-491f-8f9c-775d16605b99
handle: websiteColorGray900
instructions: ''
name: 'Website - Color - Gray 900'
searchable: false
settings:
  defaultColor: '#262626'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
