contentColumnType: string(7)
fieldGroup: f6ccb015-3533-491f-8f9c-775d16605b99
handle: websiteColorGray100
instructions: ''
name: 'Website - Color - Gray 100'
searchable: false
settings:
  defaultColor: '#f4f4f4'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
