contentColumnType: string(7)
fieldGroup: f6ccb015-3533-491f-8f9c-775d16605b99
handle: websiteColorGray700
instructions: ''
name: 'Website - Color - Gray 700'
searchable: false
settings:
  defaultColor: '#525252'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
