contentColumnType: string(7)
fieldGroup: f6ccb015-3533-491f-8f9c-775d16605b99
handle: websiteColorGray500
instructions: ''
name: 'Website - Color - Gray 500'
searchable: false
settings:
  defaultColor: '#8d8d8d'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
