assets:
  tempSubpath: temp
  tempVolumeUid: 883ab42c-10f1-4e32-a559-61f23e4e3775
dateModified: 1599007264
email:
  fromEmail: asiaspa.dev@gmail.com
  fromName: AsiaSpa
  replyToEmail: asiaspa.dev@gmail.com
  template: ''
  transportSettings:
    password: Lufad49q
    timeout: '10'
    username: asiaspa.dev@gmail.com
  transportType: craft\mail\transportadapters\Gmail
plugins:
  ad-wizard:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_ADWIZARD_LC
    schemaVersion: 2.1.0
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  async-queue:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  blitz:
    enabled: true
    schemaVersion: 3.6.6
    settings:
      apiKey: ''
      cacheControlHeader: 'public, s-maxage=31536000, max-age=0'
      cacheDuration: null
      cacheElementQueries: true
      cacheElements: true
      cachePurgerType: putyourlightson\blitz\drivers\purgers\DummyPurger
      cacheStorageSettings:
        __assoc__:
          -
            - folderPath
            - '@webroot/cache/blitz'
          -
            - createGzipFiles
            - ''
      cacheStorageType: putyourlightson\blitz\drivers\storage\FileStorage
      cacheWarmerSettings:
        __assoc__:
          -
            - concurrency
            - '3'
      cacheWarmerType: putyourlightson\blitz\drivers\warmers\GuzzleWarmer
      cachingEnabled: '1'
      clearCacheAutomatically: '1'
      customSiteUris: ''
      debug: false
      deployerType: putyourlightson\blitz\drivers\deployers\DummyDeployer
      driverJobPriority: 100
      excludedQueryStringParams:
        - gclid
        - fbclid
      excludedUriPatterns: ''
      includedUriPatterns:
        -
          __assoc__:
            -
              - uriPattern
              - '*'
      injectScriptEvent: DOMContentLoaded
      integrations:
        - putyourlightson\blitz\drivers\integrations\FeedMeIntegration
        - putyourlightson\blitz\drivers\integrations\SeomaticIntegration
      mutexTimeout: 1
      outputComments: true
      queryStringCaching: '0'
      refreshCacheAutomaticallyForGlobals: true
      refreshCacheJobPriority: 10
      refreshCacheWhenElementSavedNotLive: false
      refreshCacheWhenElementSavedUnchanged: false
      sendPoweredByHeader: true
      warmCacheAutomatically: '1'
  blitz-recommendations:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  calendarize:
    edition: standard
    enabled: true
    schemaVersion: 1.3.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  easy-search:
    edition: standard
    enabled: false
    licenseKey: $PLUGIN_EASYSEARCH_LC
    schemaVersion: 1.0.0
  elements-panel:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      expandSingles: '1'
      redirectToEntry: '1'
  feed-me:
    enabled: true
    schemaVersion: 2.1.2
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  freeform:
    edition: pro
    enabled: true
    licenseKey: $PLUGIN_FREEFOM_LC
    schemaVersion: 3.0.7
    settings:
      ajaxByDefault: '1'
      autoScrollToErrors: '1'
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      customErrorMessage: null
      customHoneypotName: null
      defaultTemplates: ''
      defaultView: submissions
      emailTemplateDirectory: _email
      emailTemplateStorage: db
      fieldDisplayOrder: name
      fillWithGet: '1'
      footerScripts: false
      formSubmitDisable: '1'
      formSubmitExpiration: null
      formTemplateDirectory: _form
      formattingTemplate: _tailwindcss.twig
      freeformHoneypot: true
      freeformHoneypotEnhancement: false
      hideBannerDemo: '1'
      hideBannerOldFreeform: false
      minimumSubmitTime: null
      pluginName: Form
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: '0'
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaKey: null
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaType: v2_checkbox
      removeNewlines: ''
      renderFormHtmlInCpViews: '1'
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      scriptInsertLocation: footer
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      showTutorial: ''
      spamFolderEnabled: false
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
  google-cloud:
    edition: standard
    enabled: true
    schemaVersion: '1.1'
  http2-server-push:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  imagehotspots:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_IMAGEHOTSPOT_LC
    schemaVersion: 1.0.0
  imager-x:
    edition: pro
    enabled: true
    licenseKey: $PLUGIN_IMAGERX_LC
    schemaVersion: 3.0.0
  logs:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  mailchimp-subscribe:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  matrixmate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  matrixtoolbar:
    edition: standard
    enabled: true
    schemaVersion: 1.0.4
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigate:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_NAVIGATE_LC
    schemaVersion: 2.4.0
  navigation:
    edition: standard
    enabled: true
    schemaVersion: 1.0.17
  oembed:
    enabled: true
    schemaVersion: 1.0.1
  queue-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-split:
    enabled: true
    schemaVersion: 1.0.0
  retour:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_RETOUR_LC
    schemaVersion: 3.0.9
  searchit:
    edition: standard
    enabled: false
    licenseKey: $PLUGIN_SEARCHIT_LC
    schemaVersion: 1.0.4
  seomatic:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_SEOMATIC_LC
    schemaVersion: 3.0.9
  sidebar-toggle:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  simplemap:
    edition: pro
    enabled: true
    licenseKey: $PLUGIN_MAP_LC
    schemaVersion: 3.4.2
    settings:
      apiKey: null
      browserApiKey: null
      disablePopulateMissingFieldData: false
      geoLocationAutoRedirect: false
      geoLocationCacheDuration: 5270400
      geoLocationService: none
      geoLocationToken: ''
      geoService: google
      geoToken: AIzaSyCLIh-0zZUM7jtfeGBqtoumMP2B8lgsssM
      mapTiles: google.roadmap
      mapToken: AIzaSyCLIh-0zZUM7jtfeGBqtoumMP2B8lgsssM
      serverApiKey: null
      unrestrictedApiKey: null
      w3wEnabled: ''
      w3wToken: ''
  snitch:
    edition: standard
    enabled: true
    schemaVersion: 2.1.0
  splash:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
    settings:
      authorField: assetUnsplashAuthor
      authorUrlField: assetUnsplashAuthorUrl
      colorField: assetUnsplashDominantColor
      volume: '8'
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  super-table:
    enabled: true
    schemaVersion: 2.2.1
  support:
    edition: standard
    enabled: true
    schemaVersion: 0.1.0
  tag-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  templatecomments:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  twig-profiler:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  venveo-bulk-edit:
    edition: standard
    enabled: true
    schemaVersion: 1.1.0
  views-work:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_VIEWSWORK_LC
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $SITE_NAME
  schemaVersion: 3.5.13
  timeZone: Asia/Hong_Kong
