field: b7bf6b01-6b0b-4d48-9c31-63404b36a897
fieldLayouts:
  2c21df96-a419-42aa-8dce-b9fedc344707:
    tabs:
      -
        elements:
          -
            fieldUid: eadd3e1f-b95d-41b6-b97f-a1c004bea539
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 959a1ff6-acd6-4f01-912a-902eee53050a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  959a1ff6-acd6-4f01-912a-902eee53050a:
    contentColumnType: text
    fieldGroup: null
    handle: answer
    instructions: ''
    name: Answer
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  eadd3e1f-b95d-41b6-b97f-a1c004bea539:
    contentColumnType: text
    fieldGroup: null
    handle: question
    instructions: ''
    name: Question
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
