field: 4be7265a-1f2f-4bbe-a6e2-10d0cfccb205
fieldLayouts:
  7104a75d-151e-4c5e-a2be-ef50810cb61d:
    tabs:
      -
        fields:
          17b940bb-1abe-4368-9ccd-ba94b9d5257a:
            required: '0'
            sortOrder: '1'
          4e7f0a84-494e-4c94-836a-1fc0a77db557:
            required: '0'
            sortOrder: '2'
          81ffaa57-a57c-43a1-abfc-c810f668fcd2:
            required: '0'
            sortOrder: '3'
          bf8d9686-a59f-47ab-88e7-f52608216e2b:
            required: '0'
            sortOrder: '0'
        name: Content
        sortOrder: '1'
fields:
  17b940bb-1abe-4368-9ccd-ba94b9d5257a:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: '1'
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4e7f0a84-494e-4c94-836a-1fc0a77db557:
    contentColumnType: string
    fieldGroup: null
    handle: heroImage
    instructions: ''
    name: 'Hero Image'
    searchable: '1'
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  81ffaa57-a57c-43a1-abfc-c810f668fcd2:
    contentColumnType: string(255)
    fieldGroup: null
    handle: hyperlink
    instructions: ''
    name: Hyperlink
    searchable: '1'
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  bf8d9686-a59f-47ab-88e7-f52608216e2b:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: '1'
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
