field: dcf1654e-9b1b-4f81-a2ae-5d31c5750d25
fieldLayouts:
  16a8afa0-b6ec-4fa8-b792-42333b40402d:
    tabs:
      -
        elements:
          -
            fieldUid: 49c5d010-deb6-4e8a-baa7-ad2d87b82917
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  49c5d010-deb6-4e8a-baa7-ad2d87b82917:
    contentColumnType: string
    fieldGroup: null
    handle: source
    instructions: ''
    name: Source
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_source}}'
      maxBlocks: '1'
      minBlocks: '1'
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
