field: 1383f2c8-f480-4dbf-8214-c554546f3f2b
fieldLayouts:
  c05b0c2c-b511-48bb-b919-18f2a7acf14a:
    tabs:
      -
        elements:
          -
            fieldUid: 47b78eee-26a2-4bf5-a380-3354130cca66
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 99438d2e-8763-429c-a327-6ebb43171682
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  47b78eee-26a2-4bf5-a380-3354130cca66:
    contentColumnType: text
    fieldGroup: null
    handle: question
    instructions: ''
    name: Question
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes:
        - 883ab42c-10f1-4e32-a559-61f23e4e3775
        - 9f801622-9f26-40c9-9126-ac4041a76554
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  99438d2e-8763-429c-a327-6ebb43171682:
    contentColumnType: text
    fieldGroup: null
    handle: answer
    instructions: ''
    name: Answer
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes:
        - 883ab42c-10f1-4e32-a559-61f23e4e3775
        - 9f801622-9f26-40c9-9126-ac4041a76554
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
