field: 8fd13f01-7952-450b-8ca6-325a4b4f4867
fieldLayouts:
  759fa279-5a52-4bea-915a-e8b5e1b0aa1a:
    tabs:
      -
        fields:
          2ef9cd0d-784e-48bd-ae19-6f7b189072f7:
            required: '0'
            sortOrder: '2'
          b633ffb7-1271-4b54-85be-a6edb1cedddb:
            required: '0'
            sortOrder: '1'
          c35b5513-a0d3-458a-8e1c-a3080b855c8d:
            required: '0'
            sortOrder: '0'
        name: Content
        sortOrder: '1'
fields:
  2ef9cd0d-784e-48bd-ae19-6f7b189072f7:
    contentColumnType: string(255)
    fieldGroup: null
    handle: hyperlink
    instructions: ''
    name: Hyperlink
    searchable: '1'
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  b633ffb7-1271-4b54-85be-a6edb1cedddb:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: '1'
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c35b5513-a0d3-458a-8e1c-a3080b855c8d:
    contentColumnType: string
    fieldGroup: null
    handle: heroImage
    instructions: ''
    name: 'Hero Image'
    searchable: '1'
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:883ab42c-10f1-4e32-a559-61f23e4e3775'
        - 'volume:9f801622-9f26-40c9-9126-ac4041a76554'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
