fieldLayouts:
  7a3cc5a0-b87c-43f3-b7e9-a1acc303bca0:
    tabs:
      -
        elements:
          -
            style: tip
            tip: 'Ads will automatically shown in cooresponding ad position. To add new ad placement / new format of ad. Contact developers for new ad placement.'
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: 236205e4-f453-4ab0-83bd-745ec2cd3e2e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 87027a3c-765e-4329-90d4-193dc2188fed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 1e9a7d45-d736-498b-a1ac-5f9e110553c9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: cdfac713-f7e7-4e44-9e62-d218d76ab674
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: 'Ad Placement'
        sortOrder: 1
handle: ad
name: Ad
