fieldLayouts:
  3d150a4d-85a8-49bf-b1c1-c5b849896e95:
    tabs:
      -
        elements:
          -
            fieldUid: f799212b-683d-49c2-acf2-8adcb685edd6
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: eed72883-2977-4af8-8576-1fe442ba702c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 5e6710fa-b19d-4c11-bc85-252d5e99f99f
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 633c8e4a-27cc-4fb1-b2e0-4660aee60c3d
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Logo
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 9bfabc16-1b6a-4dd0-b688-5c0b752244b8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 02f242d0-61e4-4c3a-a577-a90d9f484078
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 160cd5a3-d3e9-458e-b670-045102c02894
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: d701504e-6018-4a77-baf9-5f39d38d00ec
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 78f726a3-084c-4cff-af23-939c5ac873b1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 1ef1bbcf-3b4c-4a2e-8a60-700b09bfa798
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: cc775117-bfa4-468a-979d-b9c6dacb21dc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 41421cb7-dc7c-462c-97ee-2666295a847d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 5ba83214-6566-4d40-ac2f-60a9faf34dae
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: fb674aea-8262-4880-9b91-c2706c4923d2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: da8764a4-d9aa-46c8-8198-c5087b141921
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 5766ff59-5b69-4ffd-9fa3-deb4b37211d7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Color
        sortOrder: 2
      -
        elements:
          -
            style: tip
            tip: 'You need to also update the `typekit` at adobe font as well. Also, remember to include italic style for sans serif font.'
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: 7a2bf154-3263-4f8f-a6d2-f31faa6fcdff
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 7394d376-113d-4ccd-9e3f-3dcd3aeaab01
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: f6e8584b-5956-4d37-a140-1330e5d5b7e8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 2553fc2a-75cb-4cb3-aa05-53d2debc494c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 35c9a7ae-347d-4867-8632-1d2821253dcd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: cef6c7c0-7963-456e-b085-061d02804428
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 926d7504-080e-465f-9da2-9db2890ff60e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Typography
        sortOrder: 3
      -
        elements:
          -
            fieldUid: f838edc2-c252-49b3-a8ca-d352be911f97
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9864715a-4c2c-4d55-9862-2625c749393f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Global Ad'
        sortOrder: 4
handle: website
name: Website
