handle: publisher
name: Publisher
permissions:
  - accesssitewhensystemisoff
  - accesscpwhensystemisoff
  - accessplugin-navigation
  - accessplugin-retour
  - accessplugin-seomatic
  - accessplugin-sprout-forms
  - accesscp
  - registerusers
  - moderateusers
  - impersonateusers
  - editusers
  - deleteusers
  - 'publishentries:73c18577-4ee7-4d1d-be3f-133db7de04c5'
  - 'publishpeerentrydrafts:73c18577-4ee7-4d1d-be3f-133db7de04c5'
  - 'deletepeerentrydrafts:73c18577-4ee7-4d1d-be3f-133db7de04c5'
  - 'editpeerentrydrafts:73c18577-4ee7-4d1d-be3f-133db7de04c5'
  - 'editentries:73c18577-4ee7-4d1d-be3f-133db7de04c5'
  - 'createentries:c2929640-5995-4a0b-b490-deb3c54ab6d4'
  - 'publishentries:c2929640-5995-4a0b-b490-deb3c54ab6d4'
  - 'deleteentries:c2929640-5995-4a0b-b490-deb3c54ab6d4'
  - 'publishpeerentries:c2929640-5995-4a0b-b490-deb3c54ab6d4'
  - 'deletepeerentries:c2929640-5995-4a0b-b490-deb3c54ab6d4'
  - 'editpeerentries:c2929640-5995-4a0b-b490-deb3c54ab6d4'
  - 'publishpeerentrydrafts:c2929640-5995-4a0b-b490-deb3c54ab6d4'
  - 'deletepeerentrydrafts:c2929640-5995-4a0b-b490-deb3c54ab6d4'
  - 'editpeerentrydrafts:c2929640-5995-4a0b-b490-deb3c54ab6d4'
  - 'editentries:c2929640-5995-4a0b-b490-deb3c54ab6d4'
  - 'publishentries:48ef7d40-ffba-45ee-8f7a-e812985c465e'
  - 'publishpeerentrydrafts:48ef7d40-ffba-45ee-8f7a-e812985c465e'
  - 'deletepeerentrydrafts:48ef7d40-ffba-45ee-8f7a-e812985c465e'
  - 'editpeerentrydrafts:48ef7d40-ffba-45ee-8f7a-e812985c465e'
  - 'editentries:48ef7d40-ffba-45ee-8f7a-e812985c465e'
  - 'createentries:5e15a326-1e20-4d38-86df-6f2bc3183b14'
  - 'publishentries:5e15a326-1e20-4d38-86df-6f2bc3183b14'
  - 'deleteentries:5e15a326-1e20-4d38-86df-6f2bc3183b14'
  - 'publishpeerentries:5e15a326-1e20-4d38-86df-6f2bc3183b14'
  - 'deletepeerentries:5e15a326-1e20-4d38-86df-6f2bc3183b14'
  - 'editpeerentries:5e15a326-1e20-4d38-86df-6f2bc3183b14'
  - 'publishpeerentrydrafts:5e15a326-1e20-4d38-86df-6f2bc3183b14'
  - 'deletepeerentrydrafts:5e15a326-1e20-4d38-86df-6f2bc3183b14'
  - 'editpeerentrydrafts:5e15a326-1e20-4d38-86df-6f2bc3183b14'
  - 'editentries:5e15a326-1e20-4d38-86df-6f2bc3183b14'
  - 'editcategories:dc068a49-9607-4bc7-9bd1-069f279dbf76'
  - 'editcategories:b85be20d-3d22-431f-a700-c2d63cf40881'
  - 'editcategories:747402aa-105d-41d3-ace6-9e3de98971a4'
  - sproutforms-editforms
  - sproutforms-editentries
  - sproutforms-viewentries
  - sproutforms-editnotifications
  - sproutforms-viewnotifications
  - sproutforms-editreports
  - sproutforms-viewreports
  - 'seomatic:dashboard'
  - 'seomatic:global-meta:general'
  - 'seomatic:global-meta:twitter'
  - 'seomatic:global-meta:facebook'
  - 'seomatic:global-meta:robots'
  - 'seomatic:global-meta:humans'
  - 'seomatic:global-meta:ads'
  - 'seomatic:global-meta'
  - 'seomatic:content-meta:general'
  - 'seomatic:content-meta:twitter'
  - 'seomatic:content-meta:facebook'
  - 'seomatic:content-meta:sitemap'
  - 'seomatic:content-meta'
  - 'seomatic:site-settings:identity'
  - 'seomatic:site-settings:creator'
  - 'seomatic:site-settings:social'
  - 'seomatic:site-settings:sitemap'
  - 'seomatic:site-settings:miscellaneous'
  - 'seomatic:site-settings'
  - 'seomatic:tracking-scripts:googleanalytics'
  - 'seomatic:tracking-scripts:gtag'
  - 'seomatic:tracking-scripts:googletagmanager'
  - 'seomatic:tracking-scripts:facebookpixel'
  - 'seomatic:tracking-scripts:linkedininsight'
  - 'seomatic:tracking-scripts:hubspot'
  - 'seomatic:tracking-scripts'
  - 'seomatic:plugin-settings'
  - 'blitz:clear'
  - 'blitz:flush'
  - 'blitz:purge'
  - 'blitz:warm'
  - 'blitz:deploy'
  - 'blitz:refresh'
  - 'blitz:refresh-expired'
  - 'blitz:refresh-urls'
  - 'blitz:refresh-tagged'
  - navigation-createnavs
  - 'retour:dashboard'
  - 'retour:redirects'
  - 'retour:settings'
  - permission_bulkedit_entries
  - 'createentries:417974cf-15b0-4807-b344-075e1687f290'
  - 'publishentries:417974cf-15b0-4807-b344-075e1687f290'
  - 'deleteentries:417974cf-15b0-4807-b344-075e1687f290'
  - 'publishpeerentries:417974cf-15b0-4807-b344-075e1687f290'
  - 'deletepeerentries:417974cf-15b0-4807-b344-075e1687f290'
  - 'editpeerentries:417974cf-15b0-4807-b344-075e1687f290'
  - 'publishpeerentrydrafts:417974cf-15b0-4807-b344-075e1687f290'
  - 'deletepeerentrydrafts:417974cf-15b0-4807-b344-075e1687f290'
  - 'editpeerentrydrafts:417974cf-15b0-4807-b344-075e1687f290'
  - 'editentries:417974cf-15b0-4807-b344-075e1687f290'
  - 'editglobalset:94aa7177-3295-4bf7-8be0-8a81dd3c194d'
  - permission_bulkedit_assets
  - permission_bulkedit_categories
  - permission_bulkedit_users
  - 'saveassetinvolume:f6b6a0a2-13b7-4a96-892e-19f882d66b20'
  - 'createfoldersinvolume:f6b6a0a2-13b7-4a96-892e-19f882d66b20'
  - 'deletefilesandfoldersinvolume:f6b6a0a2-13b7-4a96-892e-19f882d66b20'
  - 'editimagesinvolume:f6b6a0a2-13b7-4a96-892e-19f882d66b20'
  - 'editpeerfilesinvolume:f6b6a0a2-13b7-4a96-892e-19f882d66b20'
  - 'replacepeerfilesinvolume:f6b6a0a2-13b7-4a96-892e-19f882d66b20'
  - 'deletepeerfilesinvolume:f6b6a0a2-13b7-4a96-892e-19f882d66b20'
  - 'editpeerimagesinvolume:f6b6a0a2-13b7-4a96-892e-19f882d66b20'
  - 'viewpeerfilesinvolume:f6b6a0a2-13b7-4a96-892e-19f882d66b20'
  - 'viewvolume:f6b6a0a2-13b7-4a96-892e-19f882d66b20'
  - 'saveassetinvolume:883ab42c-10f1-4e32-a559-61f23e4e3775'
  - 'createfoldersinvolume:883ab42c-10f1-4e32-a559-61f23e4e3775'
  - 'deletefilesandfoldersinvolume:883ab42c-10f1-4e32-a559-61f23e4e3775'
  - 'editimagesinvolume:883ab42c-10f1-4e32-a559-61f23e4e3775'
  - 'editpeerfilesinvolume:883ab42c-10f1-4e32-a559-61f23e4e3775'
  - 'replacepeerfilesinvolume:883ab42c-10f1-4e32-a559-61f23e4e3775'
  - 'deletepeerfilesinvolume:883ab42c-10f1-4e32-a559-61f23e4e3775'
  - 'editpeerimagesinvolume:883ab42c-10f1-4e32-a559-61f23e4e3775'
  - 'viewpeerfilesinvolume:883ab42c-10f1-4e32-a559-61f23e4e3775'
  - 'viewvolume:883ab42c-10f1-4e32-a559-61f23e4e3775'
