enableVersioning: true
handle: spa
name: Spa
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5058e36f-39fa-4fe2-982d-2a6082be4a27:
    enabledByDefault: true
    hasUrls: true
    template: _spa/_generic
    uriFormat: 'spa/{slug}'
type: channel
